name = "YACHT"
license = "Mozilla-2.0"
licenselink = "https://mozilla.org/MPL/2.0/"
description = "YACHT Another Custom Hugo Theme"
min_version = "0.110.0"

homepage = "https://github.com/ejsdotsh/yacht-hugo-theme"
demosite = ""

tags = ["blog", "minimal", "portfolio"]
features = ["dark"]

[author]
name = "e.j. sahala (they/them)"
homepage = "https://www.saha.la"
